name: Docker Build Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 🏷️ short_sha_extract
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: 🦚 Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: 👷🏾 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: 🔑 Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: eninkaduk
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 🐳 Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: eninkaduk/python-telegramp3-bot:latest, eninkaduk/python-telegramp3-bot:{{ steps.vars.outputs.sha_short }}
